### ISSUE TITLE
Problem in pathogen statues graph when increase population 

### ISSUE THREAD

**Issue by Jihadkmail** [irawinder/EpiSim#1]
Dear Ira,
First I would like to thank you for your tool which is amazing and very useful. I would like to use it to record a video to raise awareness in my community about the importance of staying home. However, I am trying to set the population number from "this.peopleTally  = 27000;" when I do so and run the simulation, I face a problem with the graph where it draws the colores just at the very top of the graph. 
sorry, I am not really a programmer but I have the basic knowledge. so I appreciate your help.
Many thanks

**Comment by irawinder** [comment]
Hi Jihad. I hope you're well and thanks for your efforts to help your community understand the situation.  I understand that you are trying to set the total population in the model to be 27,000 people? The short answer is that I don't think the model can support that many people. However, you might explain that each person in the current model could represent 10 or 20 actual people.

- Firstly, any changes to the initial conditions of the model should be made in the file "A_ConfigModel.pde". Variables in this file, as well as "A_ConfigView.pde", are the only ones that are designed to be changed.
- Currently, there is no direct way to set the total population, since the total population is calculated from the number of households and their sizes. Households are randomly generated each time the simulation is run. If you would like to adjust the total number of households, or the distribution of people in each household, consider changing the following values in 'A_ConfigModel.pde':
  - 'int N = 1;' on line 103 [i.e. changing to N = 2 will roughly double the population]
  - 'int minDwellingSize = 1;' on line 124 [i.e. min number of people in a household is 1]
  - 'int maxDwellingSize = 4;'  on line 125 [i.e. max number of people in a household is 4]
- Unfortunately, though, I don't think the simulation can handle many more people than I'm already generating by default. It's a limitation of Processing.

good luck!
